services:
  - type: web
    name: youtube-mp3
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONIOENCODING
        value: utf-8
      - key: PYTHONUNBUFFERED
        value: "1"
